name: cifar10-mlops
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - numpy=1.24.3
  - pandas=2.0.2
  - matplotlib=3.7.1
  - jupyter
  - pip
  - pip:
    - wandb==0.15.4
    - hydra-core==1.3.2
    - pytest==7.4.0
    - black==23.3.0
    - flake8==6.0.0